dataset:
  target: idf.datasets.carm_dataset.CFM_train_unpaired   # Dataset class handling paired GT / LQ folders.
  params:
    dataroot: /data/unpaired_carm/gt/train    # Root directory containing subfolders for GT and LQ images.
    #    /mnt/c/Users/250024095/Projects/unpaired_carm/gt/train
    noise_level: [2, 25]                         # Inclusive range [min, max] of sigma for AWGN.
    channel_wise_noise: False                     # If True, sample independent sigma per RGB channel.

    patch_size: 256                                    # Use full-resolution images; set integer to enable center/random cropping.
    augmentation: True                              # Whether to apply data augmentation (random flips and rotations).
    test: False                                       # Disable training-only randomizations.
    
    preload: False                                   # If True, load all images into memory at initialization.
    parallel_preload: False                          # If True and preload=True, use multiprocessing for faster load.

data_loader:
  batch_size: 80
  shuffle: true
  num_workers: 8
  drop_last: false
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true

repeat_dataset:
  times: 5

batch_transform:
  target: idf.datasets.batch_transform.IdentityBatchTransform