# Gaussian noise training dataset configuration.

dataset:
  target: idf.datasets.carm_dataset.CFM_train_paired   # Dataset class.
  params:
    dataroot: /data/ASD_persudo_paired    # Root directory of clean training images.
    lq_folder: low
    gt_folder: high
    
    patch_size: 256                               # Spatial crop size (square patches: patch_size x patch_size).
    augmentation: True                            # Apply on-the-fly geometric augmentations.
    test: False                                   # Set True to disable training-only randomizations.

    preload: False                                # If True, preload all images into RAM at initialization.
    parallel_preload: False                       # If True and preload=True, use multiprocessing for faster preload.

data_loader:
  batch_size: 80
  shuffle: true
  num_workers: 8
  drop_last: false
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true

repeat_dataset:
  times: 5

batch_transform:
  target: idf.datasets.batch_transform.IdentityBatchTransform